### ISSUE TITLE
Deprecated On Template Power file

### ISSUE THREAD

**Issue by marciesdr** [eFiction/v3_stable#3]
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; TemplatePower has a deprecated constructor in /includes/class.TemplatePower.inc.php on line 387

Used PHP 7 and below couldn't make this go away. Anyone know how to fix this?

**Comment by campZero** [comment]
Well, stupid me fixed it and never closed this topic:

The trick is to replace all Methods with the same name as their class with __construct.
See the included class.TemplatePower.inc.php.

Sorry for not having replied here sooner.

**Comment by marciesdr** [comment]
Think you may have forgotten to include it.

**Comment by campZero** [comment]
Ah crap, that's 3 times it has to be replaced, and I only have two of them done. Not sure how that came to be. Pushing right now.
Edit: git driving me a bit crazy today - I think it's up to date.
If you meant something different, let me know.
